In [1]:
import numpy as np

In [2]:
def support_poly(grid, vertices):
    try:
        return np.max(vertices @ (grid.T), axis=0)
    except Exception as e:
        print('vertices', vertices)
        print('grid', grid)
        raise e

In [3]:
vertices_a = np.array([
    [np.cos(0), np.sin(0)],
    [np.cos(0 + 2 * np.pi / 3), np.sin(0 + 2 * np.pi / 3)],
    [np.cos(0 + 4 * np.pi / 3), np.sin(0 + 4 * np.pi / 3)]
])  # A is a triangle
support_A = lambda x: support_poly(x, vertices_a)
support_B = lambda x: np.ones(len(x))

In [4]:
from src import random_spherical_grid, solve_primal
grid = random_spherical_grid(2, 4)

In [5]:
support_A(grid)

array([1.        , 0.8660254 , 0.5       , 0.8660254 , 0.60578456,
       0.90459819, 0.58294364, 0.91163569])

In [6]:
t, x = solve_primal(grid, support_A(grid), support_B(grid))
t, x

(0.9404338075296166, array([0.05956619, 0.02296336]))

In [59]:
from src import BaselineSolver, IterativeSolver
iterative_solver = IterativeSolver(2, support_A, support_B, max_iteration=100, initial_grid_size=10, number_of_gridpoints_in_cap=10, tolerance=1e-9)

In [60]:
iterative_solver.solve()

In [61]:
iterative_solver.x, iterative_solver.t

(array([ 6.63902783e-08, -3.48390136e-08]), 0.9999999336097218)

In [10]:
np.array([[1,1],[2,2],[3,3],[4,4],[5,5],[6,6]]).reshape((2, 3, 2))

array([[[1, 1],
        [2, 2],
        [3, 3]],

       [[4, 4],
        [5, 5],
        [6, 6]]])